let dataFood = [
  {
    name: "Waffle with Berries",
    price: 6.5,
    index: 0,
    quantity: 1,
    url: "../../../assets/images/food-image-0.jpg",
    description: "plate of Waffle with Berries",
  },
  {
    name: "Vanilla Bean Crème Brûlée",
    price: 7,
    index: 1,
    quantity: 1,
    url: "../../../assets/images/food-image-1.jpg",
    description: "plate of Vanilla Bean Crème Brûlée",
  },
  {
    name: "Macaron Mix of Five",
    price: 8,
    index: 2,
    quantity: 1,
    url: "../../../assets/images/food-image-2.jpg",
    description: "plate of Macaron Mix of Five",
  },
  {
    name: "Classic Tiramisu",
    price: 5.5,
    index: 3,
    quantity: 1,
    url: "../../../assets/images/food-image-3.jpg",
    description: "plate of Classic Tiramisu",
  },
  {
    name: "Pistachio Baklava",
    price: 4,
    index: 4,
    quantity: 1,
    url: "../../../assets/images/food-image-4.jpg",
    description: "plate of Pistachio Baklava",
  },
  {
    name: "Lemon Meringue Pie",
    price: 5,
    index: 5,
    quantity: 1,
    url: "../../../assets/images/food-image-5.jpg",
    description: "plate of Lemon Meringue Pie",
  },
  {
    name: "Red Velvet Cake",
    price: 4.5,
    index: 6,
    quantity: 1,
    url: "../../../assets/images/food-image-6.jpg",
    description: "plate of ",
  },
  {
    name: "Salted Caramel Brownie",
    price: 5.5,
    index: 7,
    quantity: 1,
    url: "../../../assets/images/food-image-7.jpg",
    description: "plate of ",
  },
  {
    name: "Vanilla Panna Cotta",
    price: 6.5,
    index: 8,
    quantity: 1,
    url: "../../../assets/images/food-image-8.jpg",
    description: "plate of Vanilla Panna Cotta",
  },
];

export { dataFood };
